"""Write the drafted catalogue charts into ooh-woo-game.html.
Usage (repository root): python tools/chart-builder/apply_to_game.py
Replaces only the block between the catalogue-charts markers; Twinkle's chart is never touched.
"""
import json, os, re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
HTML = os.path.join(ROOT, 'ooh-woo-game.html')
START = '// <catalogue-charts>'
END = '// </catalogue-charts>'

charts = json.load(open(os.path.join(ROOT, 'docs', 'catalogue-analysis', 'charts.json'), encoding='utf-8'))

def js(value):
    return json.dumps(value, ensure_ascii=False, separators=(',', ':'))

lines = [START,
         '// GENERATED by tools/chart-builder/apply_to_game.py from docs/catalogue-analysis/charts.json.',
         '// Each chart is drafted from that recording\'s separated vocal: t/end are seconds in the backing',
         '// file, midi is the sung pitch, ratio is lanes above baseMidi (the key\'s Do). Do not edit by hand;',
         '// fix the builder or the JSON and re-run. Listening review by the owner is pending for all of them.',
         'const CATALOGUE_CHARTS = {']
for key, c in charts.items():
    lines.append(f"  {key}: {{status:{js(c['status'])}, keyTonic:{js(c['keyTonic'])}, baseMidi:{c['displayBaseMidi']}, "
                 f"window:{js(c['laneWindow'])}, level:{js(c['level'])},")
    lines.append(f"    phrases:{js([[p['firstNote'], p['lastNote']] for p in c['phrases']])}, notes:[")
    for p in c['phrases']:
        row = c['notes'][p['firstNote']:p['lastNote'] + 1]
        lines.append('      ' + ','.join(
            '{' + f"note:{js(n['note'])},midi:{n['midi']},ratio:{n['ratio']},t:{n['t']},end:{n['end']},lyric:{js(n['lyric'])},phrase:{n['phrase']}" + '}'
            for n in row) + ',')
    lines.append('    ]},')
lines += ['};', END]

html = open(HTML, encoding='utf-8', newline='').read()
eol = '\r\n' if '\r\n' in html else '\n'                      # keep the file's existing line endings
pattern = re.compile(re.escape(START) + r'[\s\S]*?' + re.escape(END))
assert pattern.search(html), 'catalogue-charts markers not found in ooh-woo-game.html'
html = pattern.sub(lambda _: eol.join(lines), html, count=1)
open(HTML, 'w', encoding='utf-8', newline='').write(html)
print('wrote', len(charts), 'charts,', sum(len(c['notes']) for c in charts.values()), 'notes')
