"""Write the built charts (Full song + Quick play) into index.html.
Usage (repository root):
  python tools/chart-builder/apply_to_game.py             write the generated block
  python tools/chart-builder/apply_to_game.py --dry-run   show what would change, write nothing
Replaces only the block between the catalogue-charts markers. The embedded twinkle-chart (the approved
reference verse) is never touched: Twinkle's Quick play uses it directly, and its Full song chart copies
those 42 notes unchanged before the Mandarin verse.
"""
import json, os, re, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
HTML = os.path.join(ROOT, 'index.html')
START = '// <catalogue-charts>'
END = '// </catalogue-charts>'

def js(value):
    return json.dumps(value, ensure_ascii=False, separators=(',', ':'))

def block(charts):
    lines = [START,
             '// GENERATED by tools/chart-builder/apply_to_game.py from docs/catalogue-analysis/charts.json.',
             '// Do not edit by hand: correct tools/chart-builder/songs/<key>.json, rebuild, re-run.',
             '// t/end are seconds in the backing file. midi is the sung pitch; ratio is lanes above baseMidi.',
             '// modes.full = every located sung section of the recording; modes.quick = a deliberate excerpt.',
             '// Every chart is a recording-based draft until Galvin approves it by listening.',
             'const CATALOGUE_CHARTS = {']
    for key, c in charts.items():
        sections = [{'id': s['id'], 'label': s['label'], 'language': s['language'], 'kind': s['kind'],
                     'firstNote': s.get('firstNote'), 'lastNote': s.get('lastNote'),
                     'review': s.get('review', 'owner-listening-pending'),
                     **({'flag': s['qualityFlag']} if s.get('qualityFlag') else {}),
                     **({'excluded': True} if s.get('excluded') else {})} for s in c['sections']]
        modes = {}
        for name, m in c['modes'].items():
            modes[name] = {'label': m['label'], 'level': m['level'], 'firstNote': m['firstNote'], 'lastNote': m['lastNote'],
                           'laneWindow': m['laneWindow'], 'languages': m['languages'], 'seconds': m['durationSeconds'],
                           'sections': m['sections'], 'phrases': m['phrases']}
        lines.append(f"  {key}: {{status:{js(c['status'])}, keyTonic:{js(c['keyTonic'])}, baseMidi:{c['displayBaseMidi']}, "
                     f"recordingSeconds:{c['recordingSeconds']},")
        lines.append(f"    sections:{js(sections)},")
        lines.append(f"    modes:{js(modes)},")
        lines.append('    notes:[')
        for p in c['phrases']:
            row = c['notes'][p['firstNote']:p['lastNote'] + 1]
            lines.append('      ' + ','.join(
                '{' + f"id:{js(n['id'])},note:{js(n['note'])},midi:{n['midi']},ratio:{n['ratio']},t:{n['t']},end:{n['end']},"
                f"lyric:{js(n['lyric'])},phrase:{n['phrase']}" + '}' for n in row) + ',')
        lines.append('    ]},')
    lines += ['};', END]
    return lines

def main():
    dry = '--dry-run' in sys.argv
    charts = json.load(open(os.path.join(ROOT, 'docs', 'catalogue-analysis', 'charts.json'), encoding='utf-8'))
    html = open(HTML, encoding='utf-8', newline='').read()
    eol = '\r\n' if '\r\n' in html else '\n'                      # keep the file's existing line endings
    pattern = re.compile(re.escape(START) + r'[\s\S]*?' + re.escape(END))
    found = pattern.search(html)
    assert found, 'catalogue-charts markers not found in index.html'
    new = eol.join(block(charts))
    if found.group(0) == new:
        print('index.html already matches charts.json; nothing to write'); return
    old_keys = re.findall(r'^  (\w+): \{status:', found.group(0), re.M)
    print(f"generated block: {len(charts)} songs, {sum(len(c['notes']) for c in charts.values())} notes "
          f"(was {len(old_keys)} songs, {found.group(0).count('{note:') + found.group(0).count('{id:')} notes)")
    for key, c in charts.items():
        old = re.search(r'^  ' + key + r': \{[\s\S]*?^    \]\},', found.group(0), re.M)
        now = re.search(r'^  ' + key + r': \{[\s\S]*?^    \]\},', new, re.M)
        if not old or old.group(0) != now.group(0):
            f, q = c['modes']['full'], c['modes']['quick']
            print(f"  {'new' if not old else 'changed':7s} {key:13s} full {f['noteCount']:4d} notes {f['durationSeconds']:6.1f}s "
                  f"| quick {q['noteCount']:3d} notes {q['level']['start']:.1f}-{q['level']['end']:.1f}s")
    if dry:
        print('dry run: index.html not written'); return
    html = html[:found.start()] + new + html[found.end():]
    open(HTML, 'w', encoding='utf-8', newline='').write(html)
    print('wrote', HTML)

if __name__ == '__main__':
    main()
