"""Write the review material for the built charts. Usage (repository root):
  python tools/chart-builder/report.py
Outputs (both regenerated from docs/catalogue-analysis/charts.json, never edited by hand):
  docs/CATALOGUE-CORRECTION-REVIEW.md   before/after table, what was implemented, what is unresolved
  tools/catalogue-listening.html        listening page: play any section of any song, recording or vocal only
Nothing here marks a song as listened to: that is recorded only in tools/chart-builder/songs/<key>.json.
"""
import collections, json, os, sys

sys.path.insert(0, os.path.dirname(__file__))
from catalogue import ROOT, asset_paths

LANG = {'en': 'English', 'zh': 'Mandarin', 'ms': 'Malay'}
PITCH_FLAGS = ('estimators-disagree', 'octave-fold-suspect', 'unstable-pitch', 'weak-independent-voicing')

def clock(seconds):
    s = int(round(seconds)); return f'{s // 60}:{s % 60:02d}'

def song_stats(c):
    notes = c['notes']
    status = collections.Counter()
    for n in notes:
        if not n.get('lyric'): status['no-lyric'] += 1; continue
        # Twinkle's approved verse carries no per-note status: its words were approved with the chart
        for part in (n.get('lyricStatus') or 'heard').split('+'): status[part] += 1
    flagged = sum(1 for n in notes if any(f in PITCH_FLAGS for f in n.get('flags', [])))
    return {
        'notes': len(notes), 'status': status, 'pitchFlagged': flagged,
        'splits': sum(1 for n in notes if (n.get('attack') or {}).get('source') == 'measured attack'),
        'shared': sum(1 for n in notes if 'syllables-share-note' in n.get('flags', [])),
        'glides': sum(len(n.get('absorbedGlides', [])) for n in notes),
        'octave': sum(1 for n in notes if 'octave-fold-suspect' in n.get('flags', [])),
        'edits': sum(1 for n in notes if n.get('edits')),
    }

def main():
    charts = json.load(open(os.path.join(ROOT, 'docs', 'catalogue-analysis', 'charts.json'), encoding='utf-8'))
    old = json.load(open(os.path.join(ROOT, 'docs', 'catalogue-analysis', 'charts-2026-10-02-excerpts.json'), encoding='utf-8'))
    L = ['# Catalogue correction review (built 2026-10-03)', '',
         'Generated by `python tools/chart-builder/report.py` from `docs/catalogue-analysis/charts.json`. Do not edit by hand.', '',
         '## What "implemented" and "listening-verified" mean here', '',
         '- **Implemented** = the chart was rebuilt from the recording by the corrected pipeline and passed the automatic checks.',
         '- **Listening-verified** = Galvin has listened to that section and approved it. **No section of any song is '
         'listening-verified yet.** Every song and section below is `owner-listening-pending`.',
         '- Pitch flags are leads for listening. No pitch was replaced because of a flag; a pitch only changes through a '
         'recorded edit in `tools/chart-builder/songs/<key>.json` (currently: none).', '',
         '## Before and after, per song', '',
         '| Song | Before (2026-10-02 excerpt) | Full song now | Quick play now | Languages | Sections | Listening-verified |',
         '|---|---|---|---|---|---|---|']
    for key, c in charts.items():
        f, q = c['modes']['full'], c['modes']['quick']
        if key in old:
            o = old[key]; before = f"{len(o['notes'])} notes, {clock(o['level']['end'] - o['level']['start'])}, {LANG.get(o.get('language'), o.get('language'))} only"
        else:
            before = '42 notes, 0:41, English verse (approved reference, unchanged)'
        L.append(f"| {c['recording']} | {before} | {f['noteCount']} notes, {clock(f['durationSeconds'])} | "
                 f"{q['noteCount']} notes, {clock(q['durationSeconds'])} ({q['level']['start']:.1f}–{q['level']['end']:.1f} s) | "
                 f"{' + '.join(LANG[l] for l in f['languages'])} | {sum(1 for s in c['sections'] if s.get('noteCount'))} | none |")
    L += ['', '## What was implemented, per song', '',
          'Columns: **heard** = lyric confirmed by the transcription passes; **ref. spelling** = sung sound matched a '
          'reference word that was transcribed differently (homophones, Malay/English spellings); **variant** = singer '
          'sang a different word from the reference and the chart shows what was sung; **not heard** = reference word '
          'placed without transcript support; **no lyric** = note with no syllable (melisma or wordless); **split** = '
          'syllable boundaries placed at a measured attack inside one detected note; **shared** = syllables left on one '
          'note because the audio shows no attack; **pitch leads** = notes with at least one pitch flag.', '',
          '| Song | Notes | heard | ref. spelling | variant | not heard | unscripted | no lyric | split | shared | glides joined | pitch leads | of which octave leads |',
          '|---|---|---|---|---|---|---|---|---|---|---|---|---|']
    for key, c in charts.items():
        s = song_stats(c); st = s['status']
        L.append(f"| {c['recording']} | {s['notes']} | {st['heard'] + st['heard-vocable']} | {st['reference-spelling']} | "
                 f"{st['sung-variant'] + st['extra-sung']} | {st['not-heard']} | {st['unscripted-heard']} | {st['no-lyric']} | "
                 f"{s['splits']} | {s['shared']} | {s['glides']} | {s['pitchFlagged']} | {s['octave']} |")
    L += ['', '## Unresolved regions (listen to these first)', '']
    for key, c in charts.items():
        rows = []
        for s in c['sections']:
            if s.get('qualityFlag'):
                q = s['quality']
                why = (f"{round(100 * q['pitchFlaggedShare'])}% of notes carry a pitch flag, {round(100 * q['largeLeapShare'])}% large leaps"
                       if s['qualityFlag'] == 'pitch-unreliable' else f"only {round(100 * q['lyricLabelledShare'])}% of notes have a lyric")
                rows.append(f"  - `{s['id']}` {s['label']} ({LANG.get(s['language'], s['language'])}, {s['start']:.1f}–{s['end']:.1f} s): "
                            f"**{s['qualityFlag']}** — {why}")
            if s.get('excluded'):
                rows.append(f"  - `{s['id']}` {s['label']} ({s['start']:.1f}–{s['end']:.1f} s): left out — {s['excluded']}")
            if s.get('kind') == 'unscripted' and s.get('noteCount'):
                rows.append(f"  - `{s['id']}` {s['label']} ({s['start']:.1f}–{s['end']:.1f} s): unscripted singing, no reference lyrics; "
                            f"{s['noteCount']} notes")
            for v in s.get('variants', []) or []:
                rows.append(f"  - `{s['id']}` sung variant: {json.dumps(v, ensure_ascii=False)}")
        for a in c.get('absentSections', []):
            rows.append(f"  - reference section not found in the recording: {json.dumps(a, ensure_ascii=False)}")
        dropped = c.get('droppedLyricUnits', [])
        if dropped: rows.append(f'  - {len(dropped)} reference syllables could not be placed on a note (listed in charts.json `droppedLyricUnits`)')
        if rows: L += [f"- **{c['recording']}**"] + rows
    L += ['', '## How to listen', '',
          '1. Start the game server (`start-game.bat`).',
          '2. Open <http://localhost:8080/tools/catalogue-listening.html>. Pick a song, press a section: it plays that '
          'part of the recording (or the singer only) and shows the charted notes and words.',
          '3. In the game, play the song with "Hear my guide melody" ticked, in Full song and in Quick play.',
          '4. Tell Claude which sections are good and what is off. Approval is written into '
          '`tools/chart-builder/songs/<key>.json`; nothing else can mark a section verified.', '']
    out = os.path.join(ROOT, 'docs', 'CATALOGUE-CORRECTION-REVIEW.md')
    open(out, 'w', encoding='utf-8', newline='\n').write('\n'.join(L))
    print('wrote', out)

    data = {}
    for key, c in charts.items():
        paths = asset_paths(key)
        data[key] = {'name': c['recording'], 'source': '../' + paths['source'], 'backing': '../' + paths['backing'], 'vocal': '../' + paths['vocal'],
                     'quick': c['modes']['quick']['level'], 'full': c['modes']['full']['level'],
                     'sections': [{'id': s['id'], 'label': s['label'], 'language': LANG.get(s['language'], s['language']),
                                   'start': s['start'], 'end': s['end'], 'review': s.get('review'), 'flag': s.get('qualityFlag'),
                                   'excluded': s.get('excluded'), 'first': s.get('firstNote'), 'last': s.get('lastNote')}
                                  for s in c['sections']],
                     'phrases': [[p['firstNote'], p['lastNote']] for p in c['phrases']],
                     'notes': [[n['t'], n['end'], n['note'], n['lyric'] or '', ','.join(n.get('flags', [])), n.get('lyricStatus') or ''] for n in c['notes']]}
    page = PAGE.replace('/*DATA*/', json.dumps(data, ensure_ascii=False, separators=(',', ':')))
    out = os.path.join(ROOT, 'tools', 'catalogue-listening.html')
    open(out, 'w', encoding='utf-8', newline='\n').write(page)
    print('wrote', out)

PAGE = '''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>OohWoo listening review</title>
<!-- GENERATED by tools/chart-builder/report.py. Do not edit by hand. -->
<style>
 body{font-family:system-ui,sans-serif;background:#10241c;color:#e8f5ee;margin:0;padding:16px;max-width:980px;margin:auto}
 h1{font-size:22px} select,button{font-size:15px;padding:6px 10px;border-radius:8px;border:1px solid #52b788;background:#173d30;color:#fff;cursor:pointer}
 .sec{border:1px solid #2d6a4f;border-radius:10px;padding:10px;margin:10px 0}
 .sec h3{margin:0 0 6px;font-size:16px} .flag{color:#ffb4a2;font-weight:700} .pending{color:#ffe66d}
 .line{margin:4px 0;line-height:2}
 .n{display:inline-block;border:1px solid #2d6a4f;border-radius:6px;padding:0 5px;margin:1px;font-size:13px;cursor:pointer}
 .n small{color:#95d5b2;display:block;font-size:10px;line-height:1.1} .n.lead{border-color:#ffb4a2} .n.weak{font-style:italic;color:#b7e4c7}
 .n.on{background:#ffe66d;color:#10241c} .n.on small{color:#10241c}
 #bar{position:sticky;top:0;background:#10241c;padding:8px 0;border-bottom:1px solid #2d6a4f;z-index:2}
</style></head><body>
<div id="bar"><h1>OohWoo listening review</h1>
 <select id="song"></select>
 <label><input type="radio" name="src" value="source" checked> Singer + music</label>
 <label><input type="radio" name="src" value="vocal"> Singer only</label>
 <label><input type="radio" name="src" value="backing"> Music only (what the game plays)</label>
 <button id="stop">Stop</button> <span id="now"></span>
 <div style="font-size:12px;color:#b7e4c7;margin-top:4px">♪ = a sung note with no word of its own (a held or sliding voice). Red border = pitch lead to listen for. Italic = word placed without transcript support.
 Click a note to play from there. Nothing on this page records approval: tell Claude what you heard.</div></div>
<div id="out"></div><audio id="a"></audio>
<script>
const DATA=/*DATA*/;
const a=document.getElementById('a'),out=document.getElementById('out'),song=document.getElementById('song'),now=document.getElementById('now');
let stopAt=null,key=null;
for(const k in DATA)song.add(new Option(DATA[k].name,k));
const src=()=>document.querySelector('input[name=src]:checked').value;
// The game's simple local server cannot jump into the middle of a file, so each file is fetched whole first.
const blobs={};let loaded=null;
async function play(from,to){const file=DATA[key][src()];
 if(!blobs[file]){now.textContent='loading…';blobs[file]=URL.createObjectURL(await (await fetch(file)).blob())}
 const go=()=>{a.currentTime=from;stopAt=to;a.play()};
 if(loaded!==file){loaded=file;a.src=blobs[file];a.addEventListener('loadedmetadata',go,{once:true})}else go();}
function fmt(t){return Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0')}
function render(){key=song.value;const d=DATA[key];a.pause();let h='<p><button data-a="'+d.full.start+'" data-b="'+d.full.end+'">Play Full song ('+fmt(d.full.end-d.full.start)+')</button> '+
 '<button data-a="'+d.quick.start+'" data-b="'+d.quick.end+'">Play Quick play part ('+fmt(d.quick.end-d.quick.start)+')</button></p>';
 for(const s of d.sections){h+='<div class="sec"><h3>'+s.label+' · '+s.language+' · '+fmt(s.start)+'–'+fmt(s.end)+
  ' <button data-a="'+Math.max(0,s.start-1)+'" data-b="'+(s.end+0.5)+'">Play</button> <span class="pending">'+(s.review||'')+'</span>'+
  (s.flag?' <span class="flag">'+s.flag+'</span>':'')+'</h3>';
  if(s.excluded)h+='<div class="flag">Left out of the chart: '+s.excluded+'</div>';
  if(s.first!=null)for(const [p,q] of d.phrases){if(p<s.first||p>s.last)continue;h+='<div class="line">';
   for(let i=p;i<=q;i++){const n=d.notes[i];h+='<span class="n'+(/disagree|octave|unstable|weak-ind/.test(n[4])?' lead':'')+(/not-heard/.test(n[5])?' weak':'')+
    '" data-i="'+i+'" data-a="'+n[0]+'" data-b="'+(s.end+0.5)+'" title="'+n[0]+'s '+n[4]+' '+n[5]+'">'+(n[3]||'♪')+'<small>'+n[2]+'</small></span>'}h+='</div>'}
  h+='</div>'}
 out.innerHTML=h}
out.addEventListener('click',e=>{const t=e.target.closest('[data-a]');if(t)play(+t.dataset.a,+t.dataset.b)});
document.getElementById('stop').onclick=()=>a.pause();song.onchange=render;
a.addEventListener('timeupdate',()=>{if(stopAt!=null&&a.currentTime>=stopAt){a.pause();stopAt=null}now.textContent=fmt(a.currentTime);
 const t=a.currentTime;for(const el of out.querySelectorAll('.n')){const n=DATA[key].notes[el.dataset.i];el.classList.toggle('on',t>=n[0]&&t<n[1])}});
render();
</script></body></html>
'''

if __name__ == '__main__':
    main()
